name: booklub
description: "Booklub é uma plataforma social dedicada a conectar leitores em clubes de leitura. O objetivo é proporcionar um ambiente colaborativo onde membros possam discutir livros, definir leituras mensais, agendar encontros e compartilhar seu progresso de leitura."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^15.1.1
  provider: ^6.1.4
  sliver_tools: ^0.2.12
  json_annotation: ^4.9.0
  file_picker: ^10.1.9
  http: ^1.4.0
  logger: ^2.5.0
  intl: ^0.20.2
  flutter_secure_storage: ^9.2.4
  mime: ^2.0.0
  http_parser: ^4.1.2
  lottie: ^2.7.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.9.5
  build_runner: ^2.4.15
  flutter_native_splash: ^2.4.0

flutter_native_splash:
  android: true
  ios: true
  web: true

  color: "#ffffff"
  color_dark: "#042a49"
  fullscreen: true

  android_12:
    color: "#ffffff"
    color_dark: "#042a49"



flutter:
  uses-material-design: true
  fonts:
    - family: Navicula
      fonts:
        - asset: assets/fonts/Navicula.ttf
  assets:
    - assets/
    - assets/images/
    - assets/animations/

json_serializable:
  generic_argument_factories: true
