name: booklub
description: "Booklub é uma plataforma social dedicada a conectar leitores em clubes de leitura. O objetivo é proporcionar um ambiente colaborativo onde membros possam discutir livros, definir leituras mensais, agendar encontros e compartilhar seu progresso de leitura."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^14.8.1
  provider: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
